### ISSUE TITLE
User feedback and User search.Reporting porn page/site for safe search.Banning malicious sites.And user can vote for site/page.2. User can submit data to database directly (also a credit system).

### ISSUE THREAD

**Issue by blurHY** [v4ww/Horizon#6]
This is a voting system.The issue is how to ensure the user is not a spammer.Maybe we need a credit system.Or i can use my spider to crawl the relationships of users that is start from nofish to generate a table of trusted users.And a blacklist for confirmed spammer (just content.json).

- [ ] Voting system to anti-bot
- [ ] User interface for voting and for user search
- [ ] Report porn/malicious zite/pages
- [ ] Use could submit zite/pages

**Comment by slrslr** [comment]
i think some bot protected voting system for the Zeronet would be good, though unsure if that is possible, **[there](https://github.com/HelloZeroNet/ZeroNet/issues/1310)** are some ideas for zeronet itself. Regarding reporting system for the search engine, as a non-programmer i am unsure how well it can be implemented without Zeronet having it included in itself. Such system may be too complex to be worthy to make it for search engine. I would rather see it more important on content sites like ZeroMe or KopyKate.
